apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  namespace: default
data:
  DATABASE_STRING: >-
    mongodb+srv://anderson-giusti:dfpk2OITruTEU2cY@cluster0.0iqosq4.mongodb.net/?retryWrites=true&w=majority
binaryData: {}