apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: br.icr.io/test-web/web:0.0.1
        ports:
        - containerPort: 3000
        
